# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "David Fox"
description: > # this means to ignore newlines until "email:"
   Software Developer, Musician, DJ, Artist

email: me@dfox.io
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/background.jpg"

name: 'David Fox'
author: 'David Fox'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://dfox.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@d_m_fox'

gallery_dir: galleries
gallery_title_prefix: 'Gallery: '
galleries_title: 'Image Galleries'
galleries:
  sculpture:
    best_image: 'untitled-closeup.jpg'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/d_m_fox
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dfox
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
